#:schema node_modules/wrangler/config-schema.json
name = "dingyue"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "8ca5bd457ba347708126b0bdea256f7c" }
]

[assets]
directory = "./public"
